### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by brmzkw** [mardiros/pyshop#49]
You're using features of [pyramid 1.5](http://docs.pylonsproject.org/docs/pyramid/en/latest/api/request.html#pyramid.request.Request.has_permission) but depend on [pyramid >=1.2](https://github.com/mardiros/pyshop/blob/master/setup.py#L20) which is working fine for new installations, since pip downloads the last version released, but not for existing installations since the dependency is satisfied when pyramid <1.5 but >=1.2 is already installed.

Can you consider update the setup.py and depend on pyramid >=1.5?

**Comment by mardiros** [comment]
Yes you are right, I broke the pyramid < 1.5 compatibility.

**Comment by mardiros** [comment]
Release 1.2.2
