### ISSUE TITLE
Instructions on docker setup

### ISSUE THREAD

**Issue by shivanshukumar** [mardiros/pyshop#58]
could you please provide some detailed instructions on how to use the docker image?
and on a slightly different note, what makes it not production ready?

**Comment by mardiros** [comment]
> could you please provide some detailed instructions on how to use the docker image?

Done here: a3f9bbe05f859d62cce396d0db5043574d0bc6b4

I have also forget to mention that the image exists on the docker public registry!

> and on a slightly different note, what makes it not production ready?
It could work on production, I don't run any docker image on production right now,
but lets do it and give me your feedback !
