### ISSUE TITLE
pyshop didn't find local packages by using pip install

### ISSUE THREAD

**Issue by Janislav** [mardiros/pyshop#61]
Problem
=======

I want to use pyhsop for internal deployment of our python packages. I created a instance of pyshop and deployed some of our packages to the pyshop server. Afterwards i tired to use pip to install these packages on my local system. The result is that the package is not available

    (test)❯ pip install nexiles.gateway.fileservice
        Downloading/unpacking nexiles.gateway.fileservice
            Could not find any downloads that satisfy the requirement       
        nexiles.gateway.fileservice
        No distributions at all found for nexiles.gateway.fileservice
        Storing complete log in /Users/jboerner/.pip/pip.log

But as you can see in the UI of pyshop the packages are available on the server
![screen shot 2015-07-15 at 10 30 53](https://cloud.githubusercontent.com/assets/1682130/8694109/c5075e46-2adc-11e5-8223-a2a91e636105.png)

I also use the right pip configuration

    [global]
    # when mirroring a package, pyshop retrieves information from PyPI and
    # stores it in its database. Be patient, it is not so long.
    default-timeout = 120
    timeout = 120

    [install]
    index-url = http://admin:admin@localhost:9000/simple/

And if we have a look on the server log, we can see that response is actually positiv

    2015-07-15 10:36:34,690 INFO  [pyshop.security][Dummy-1] [127.0.0.1] GET http://localhost:9000/simple/nexiles.gateway.fileservice/
    2015-07-15 10:36:34,708 INFO  [pyshop.security][Dummy-2] [127.0.0.1] GET http://localhost:9000/simple/nexiles.gateway.fileservice/
    2015-07-15 10:36:34,900 INFO  [pyshop.views.base][Dummy-2] dispatch view Show

Any idea why this is not working?

**Comment by mardiros** [comment]
If you browse http://localhost:9000/simple/nexiles.gateway.fileservice/
(with your browser)
Do you have a the tarball/wheel inside ?

**Comment by Janislav** [comment]
I distribut as an egg but yes i can browse and download it.

![screen shot 2015-07-15 at 12 22 35](https://cloud.githubusercontent.com/assets/1682130/8696393/4599ba36-2aec-11e5-9d5c-58aab4577aea.png)

**Comment by mardiros** [comment]
Oh, I never tests eggs in fact.
Can you test with uploading a sdist instead ?

**Comment by Janislav** [comment]
OK... I tested with sdist and it worked :) Like it seems it's just not possible to install eggs via pip at all. Also NOT from pypi. We will use wheels instead, they also work. Thanks for the fast reply. Have a nice day :).

**Comment by mardiros** [comment]
That makes sense
:)
