### ISSUE TITLE
How to force mirrored package updates

### ISSUE THREAD

**Issue by godber** [mardiros/pyshop#63]
I've been using pyshop for a while now and its worked well.  I am confused about how I can force a mirrored package to grab the latest version in PyPI.

https://pypi.python.org/pypi?name=planetary_test_data&version=0.3.2&:action=display

It appears if I wait a day then the package will update.  Is there a way to force a package to update?  I've tried purging a package and refreshing a package without the desired effect.

**Comment by hkraal** [comment]
The TTL is defined in the pyshop.ini:
    mirror.cache.ttl = 24

This ttl is the time in hours between updates which is being checked in [simple.py#L301](https://github.com/mardiros/pyshop/blob/master/pyshop/views/simple.py#L301). Seems you could adjust the ttl to "0" to force an update of all packages or set the date of the update_at field of the Package model to something less than now() - mirror.cache.ttl.

**Comment by godber** [comment]
Thanks!
