### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by kenahoo** [mardiros/pyshop#77]
I hit a snag pretty early during the installation instructions - after doing `pip install "pyshop[waitress]"` (which looked successful), the next step should be `cp pyshop.sample.ini pyshop.ini`, but no such file exists:

```
(pyshop) [KenMacBook-2:/tmp/pyshop] % ls -l
total 8
drwxr-xr-x  51 kwilliams  wheel  1734 Mar 28 17:01 bin/
drwxr-xr-x   3 kwilliams  wheel   102 Mar 28 17:00 include/
drwxr-xr-x   3 kwilliams  wheel   102 Mar 28 17:00 lib/
-rw-r--r--   1 kwilliams  wheel    60 Mar 28 17:00 pip-selfcheck.json
```

Am I supposed to find this file somewhere else?

**Comment by kenahoo** [comment]
I figured maybe I could download the `pyshop.ini` file from https://github.com/mardiros/pyshop/blob/master/pyshop.sample.ini and continue, but I ran into an error starting the server:

```
% pyshop_setup pyshop.ini
% pserve pyshop.ini start --log-file=pyshop.log
usage: pserve [-h] [-n NAME] [-s SERVER_TYPE] [--server-name SECTION_NAME]
              [--reload] [--reload-interval RELOAD_INTERVAL] [-b] [-v] [-q]
              [config_uri] [config_vars [config_vars ...]]
pserve: error: unrecognized arguments: --log-file=pyshop.log
```

Are the instructions not up to date with the code?

**Comment by mardiros** [comment]
@kenahoo 

In fact it used to works,

but it appears that it is not working anymore with pip.

**Comment by mardiros** [comment]
@kenahoo 

I asking myself if it has works one day... can't find a pip version that works properly...

issues exists on many place...

https://github.com/pypa/sampleproject/issues/30

**Comment by mardiros** [comment]
I've update the README to explain to download it in case it is not working

**Comment by kenahoo** [comment]
Cool, thanks, I also had much better luck switching to Python3 rather than Python2.
