### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by Kyrluckechuck** [mardiros/pyshop#79]
Hey there,
With the 1.2.4 update, it seems that it's not quite supporting Python3 yet, at least not the pyramid package xmlrpc!

>user@pyshop:~/pyshop-1.2.4$ pserve pyshop.ini
>Traceback (most recent call last):
>  File "/home/user/pyshop-1.2.4/lib/python3.5/site-packages/pyramid/path.py", line 380, in >_.zope_dottedname_style
>    found = getattr(found, n)
>AttributeError: module 'pyshop.views' has no attribute 'xmlrpc'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "/home/user/pyshop-1.2.4/lib/python3.5/site-packages/pyshop/views/xmlrpc.py", line 11, in ><module>
>    from pyramid_xmlrpc import XMLRPCView
>  File "/home/user/pyshop-1.2.4/lib/python3.5/site-packages/pyramid_xmlrpc/__init__.py", line 1, in ><module>
>    import xmlrpclib
>ImportError: No module named 'xmlrpclib'

If I missed something in your Python3 setup guide, just let me know, but that was following it as I saw it!

Working under Python2.7 of course though

**Comment by mardiros** [comment]
https://github.com/mardiros/pyshop/blob/master/README.rst#configuring-your-environment
```
Note

The search funciton is not working with Python 3
```

pyramid_xmlrpc is not python 3 compatible

and it has to be replaced with the lib pyramid_rpc.
