### ISSUE TITLE
Supporting Search Results With Hyphens (Replace with Underscores)

### ISSUE THREAD

**Issue by Kyrluckechuck** [mardiros/pyshop#80]
After some weird testing, it seems I've come across an edge case that pip accounts for using the normal pypi.python.org index, but Pyshop does not (yet).

When using the index for Pyshop, I was trying to install pylint, but it kept failing about being unable to find any matches for 'backports-functools-lru-cache'. After commenting out my indexer and going directly to pypi.python.org, it found it immediately, leading me to believe it was a fault with Pyshop. After investigating the logged outputs, I came across this:

`
INFO  [pyshop.security][waitress] [10.1.22.95] GET http://pyshop.<company>.com/simple/backports-functools-lru-cache/
INFO  [pyshop.security][waitress] [10.1.22.95] GET http://pyshop.<company>.com/simple/backports-functools-lru-cache/
INFO  [pyshop.views.base][waitress] dispatch view Show
INFO  [pyshop.views.base][waitress] dispatch view Show
INFO  [pyshop.views.simple][waitress] refresh package backports-functools-lru-cache
INFO  [pyshop.views.simple][waitress] refresh package backports-functools-lru-cache
DEBUG [urllib3.connectionpool][waitress] Starting new HTTPS connection (1): pypi.python.org
DEBUG [urllib3.connectionpool][waitress] https://pypi.python.org:443 "POST /pypi HTTP/1.1" 200 None
DEBUG [urllib3.connectionpool][waitress] Starting new HTTPS connection (1): pypi.python.org
DEBUG [urllib3.connectionpool][waitress] https://pypi.python.org:443 "POST /pypi HTTP/1.1" 200 None
DEBUG [pyshop.views.simple][waitress] Found 151, matched 0
DEBUG [pyshop.views.simple][waitress] Found 151, matched 0
DEBUG [urllib3.connectionpool][waitress] Starting new HTTPS connection (1): pypi.python.org
DEBUG [urllib3.connectionpool][waitress] https://pypi.python.org:443 "POST /pypi HTTP/1.1" 200 None
DEBUG [pyshop.views.simple][waitress] Found 151, matched 0
DEBUG [pyshop.views.simple][waitress] Found 151, matched 0
INFO  [pyshop.views.simple][waitress] package backports-functools-lru-cache has no versions
INFO  [pyshop.views.simple][waitress] package backports-functools-lru-cache has no versions
`

The offending hyphen's ('-') in the name of the search seem to cause Pyshop not to register the package (It finds 151 results that potentially match the package name, but none are exact matches due to the hyphens).

From what I can tell from searching using pypi.python.org though, hyphens and underscores are interchangeable (well, hyphens get replaced with underscores)

Looking forward to this fix!

**Comment by jmellor** [comment]
And another one:
$ pip install browsepy
Collecting browsepy
  Downloading https://pyshop.esentire.com/repository/4716/browsepy-0.5.3.tar.gz (207kB)
    100% |████████████████████████████████| 215kB 4.7MB/s 
Requirement already satisfied: flask in /home/jkyryliuk/dev/venv/lib/python2.7/site-packages (from browsepy)
Collecting unicategories (from browsepy)
  Downloading https://pyshop.esentire.com/repository/4717/unicategories-0.0.5.tar.gz
Collecting scandir (from browsepy)
  Downloading https://pyshop.esentire.com/repository/4724/scandir-1.5.tar.gz
Collecting backports.shutil_get_terminal_size (from browsepy)
  Could not find a version that satisfies the requirement backports.shutil_get_terminal_size (from browsepy) (from versions: )
No matching distribution found for backports.shutil_get_terminal_size (from browsepy)

**Comment by Kyrluckechuck** [comment]
Well it seems I was partially wrong -- This is their response to DevPi breaking:
https://github.com/pypa/pip/issues/3666

**Comment by mardiros** [comment]
@Kyrluckechuck 

I've just use the simple view that properly find the name of the package, works simpler and better than the PyPI API

**Comment by jmellor** [comment]
Any idea when this change is going to make it into the next release version?

**Comment by mardiros** [comment]
@jmellor 

I will do a release soon

**Comment by mardiros** [comment]
DONE !
And also add the support of xmlrpc api for search
