### ISSUE TITLE
Is there a way to stop Pyshop from mirroring EVERY version of a package?

### ISSUE THREAD

**Issue by odbawler** [mardiros/pyshop#87]
I'm currently using pyshop and its working well, but the one issue I have is time. I have currently had to set the default timeout to 240 seconds, and for a package with 15+ dependencies it can take over half an hour to download and mirror each version!

Is there a way to only mirror the specific version asked for or the latest version if one is not specified?

**Comment by mardiros** [comment]
There is actually no way to do that.
And to do that properly, It is lots of work, and a new strategy to handle how and when to mirror a package. Event it is really the right way, I have no time and need to do that currently.
